create extension if not exists pgcrypto;

create table settings (
  id int primary key default 1 check (id = 1),
  display_name text not null default 'Boss',
  completion_style text not null default 'dramatic' check (completion_style in ('dramatic','hype','calm')),
  time_study_minutes int check (time_study_minutes in (5,15,30,45,60)),
  default_minutes int not null default 25,
  default_lock text not null default 'hard' check (default_lock in ('none','soft','hard')),
  -- optional evening reminder target for the wind down card, e.g. "21:30"
  wind_down_time text not null default '',
  -- SPEC 8.15: which mode the helper flows open in. 'ai' still needs the
  -- Anthropic key configured in Vercel; without it the settings toggle
  -- refuses to switch (the key itself never reaches the browser).
  helper_mode text not null default 'scripted' check (helper_mode in ('scripted','ai'))
);
insert into settings (id) values (1);

create table projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  notes text not null default '',
  position int not null default 0,
  created_at timestamptz not null default now()
);

-- parent_task_id null = task; not null = subtask (one level only)
create table tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  parent_task_id uuid references tasks(id) on delete cascade,
  title text not null,
  done boolean not null default false,
  notes text not null default '',
  position int not null default 0,
  created_at timestamptz not null default now()
);

create table links (
  id uuid primary key default gen_random_uuid(),
  owner_type text not null check (owner_type in ('project','task')),
  owner_id uuid not null,
  name text not null,
  url text not null,
  created_at timestamptz not null default now()
);

-- dated snippets attached to a project/task/subtask (from notes, right-click, wind down)
create table note_snippets (
  id uuid primary key default gen_random_uuid(),
  owner_type text not null check (owner_type in ('project','task')),
  owner_id uuid not null,
  content text not null,
  context text not null default '',
  source text not null default 'manual' check (source in ('manual','note','page','wind_down')),
  created_at timestamptz not null default now()
);

-- Simple Notes: first line of body is the title
create table notes (
  id uuid primary key default gen_random_uuid(),
  body text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Deleting a project or task removes its links and note_snippets too
-- (SPEC 8.2: "Deleting a project ... cascades"). The owner columns are
-- polymorphic (project or task) and cannot carry a foreign key, so this
-- trigger is the ON DELETE CASCADE equivalent: atomic with the delete and
-- effective for every delete path. Cascaded deletes fire row-level triggers
-- as well, so a project delete also cleans its tasks' and subtasks' rows.
-- Session history is kept on purpose (sessions.task_id / project_id are
-- ON DELETE SET NULL).
create or replace function delete_owner_links_and_snippets() returns trigger
language plpgsql as $$
begin
  -- owner_type stores the singular kind ('project' | 'task'); TG_TABLE_NAME
  -- is the plural table name this trigger fired on.
  delete from links
    where owner_type = (case tg_table_name when 'projects' then 'project' when 'tasks' then 'task' end)
      and owner_id = old.id;
  delete from note_snippets
    where owner_type = (case tg_table_name when 'projects' then 'project' when 'tasks' then 'task' end)
      and owner_id = old.id;
  return old;
end;
$$;

drop trigger if exists delete_owner_links_snippets on projects;
create trigger delete_owner_links_snippets
  after delete on projects
  for each row execute function delete_owner_links_and_snippets();

drop trigger if exists delete_owner_links_snippets on tasks;
create trigger delete_owner_links_snippets
  after delete on tasks
  for each row execute function delete_owner_links_and_snippets();

create table blocked_sites (
  id uuid primary key default gen_random_uuid(),
  domain text not null unique,
  created_at timestamptz not null default now()
);

create table sessions (
  id uuid primary key,                       -- generated by the extension
  project_id uuid references projects(id) on delete set null,
  task_id uuid references tasks(id) on delete set null,
  misc_task_id uuid,
  label text not null default '',            -- e.g. "I'm stuck 5 min start"
  lock_mode text not null check (lock_mode in ('none','soft','hard')),
  planned_seconds int not null,
  added_seconds int not null default 0,
  active_seconds int not null,               -- excludes paused time
  started_at timestamptz not null,
  ended_at timestamptz not null
);

create table infractions (
  id uuid primary key,                       -- generated where it happened
  session_id uuid,
  kind text not null check (kind in ('site','manual')),
  detail text not null,                      -- domain, or typed text like "phone"
  occurred_at timestamptz not null
);

create table open_loops (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('loop','decision')),
  text text not null,
  created_at timestamptz not null default now()
);

create table misc_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  done boolean not null default false,
  position int not null default 0,
  created_at timestamptz not null default now()
);

create table time_studies (
  id uuid primary key default gen_random_uuid(),
  text text not null,
  occurred_at timestamptz not null default now()
);

-- one row per evening wind down; plan_date = the day being planned (tomorrow)
create table day_plans (
  id uuid primary key default gen_random_uuid(),
  plan_date date not null unique,
  start_time text not null default '',
  location text not null default '',
  prepped boolean not null default false,
  created_at timestamptz not null default now()
);

create table day_plan_tasks (
  plan_id uuid not null references day_plans(id) on delete cascade,
  task_id uuid not null references tasks(id) on delete cascade,
  position int not null default 0,
  primary key (plan_id, task_id)
);

-- the review answers for a given day
create table day_reviews (
  id uuid primary key default gen_random_uuid(),
  review_date date not null unique,
  done_today text not null default '',
  finished_goal boolean,
  best_use boolean,
  best_use_note text not null default '',
  learned text not null default '',
  eod_sent_at timestamptz,
  created_at timestamptz not null default now()
);

-- Lock everything down: RLS on, no policies, so only the service role (server) can read/write.
do $$ declare t text; begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table %I enable row level security', t);
    execute format('grant all on table %I to service_role', t);
  end loop;
end $$;

-- Wind down setting (T6a-1): idempotent, safe for databases that already ran
-- the original script.
alter table settings add column if not exists wind_down_time text not null default '';
grant all on table settings to service_role;
